//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DönemBitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Motion
    {
        public int MotionId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> Member { get; set; }
        public string PurchaseDate { get; set; }
        public string ReturnDate { get; set; }
        public string RegisterDate { get; set; }
        public Nullable<int> Employee { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Employee Employee1 { get; set; }
        public virtual Member Member1 { get; set; }
    }
}
