//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DönemBitirme.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MotionLog
    {
        public int MotionLogId { get; set; }
        public Nullable<int> MotionId { get; set; }
        public Nullable<int> BookId { get; set; }
        public Nullable<int> Member { get; set; }
        public Nullable<int> Employee { get; set; }
        public string PurchaseDate { get; set; }
        public string ReturnDate { get; set; }
        public string RegisterDate { get; set; }
        public string log_islem { get; set; }
        public System.DateTime log_tarih { get; set; }
        public string log_olusturan { get; set; }
        public string log_ip { get; set; }
    }
}
